#version: '3'
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    volumes:
      - /Users/javiergonzalezalvarez/DAM2/SGE/ODOO/data:/var/lib/postgresql/data
  odoo:
    image: odoo:16
    container_name: odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=1234
    ports:
      - '8069:8069'
    volumes:
      - /Users/javiergonzalezalvarez/DAM2/SGE/ODOO/addons:/mnt/extra-addons
      - /Users/javiergonzalezalvarez/DAM2/SGE/ODOO/filestore:/var/lib/odoo/filestore
      - /Users/javiergonzalezalvarez/DAM2/SGE/ODOO/sessions:/var/lib/odoo/sessions
    depends_on:
      - db
    command: --dev=all
